INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('20','Transferências à União');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('22','Execução Orçamentária Delegada à União');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('30','Transferências a Estados e ao Distrito Federal');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('31','Transferências a Estados e ao Distrito Federal - Fundo a Fundo');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('32','Execução Orçamentária Delegada a Estados e ao Distrito Federal');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('35','Transferências Fundo a Fundo aos Estados e ao Distrito Federal à conta de recursos de que tratam os §§ 1o e 2o do art. 24 da Lei Complementar no 141, de 2012');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('36','Transferências Fundo a Fundo aos Estados e ao Distrito Federal à conta de recursos de que trata o art. 25 da Lei Complementar no 141, de 2012');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('40','Transferências a Municípios');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('41','Transferências a Municípios - Fundo a Fundo');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('42','Execução Orçamentária Delegada a Municípios');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('45','Transferências Fundo a Fundo aos Municípios à conta de recursos de que tratam os §§ 1o e 2o do rt. 24 da Lei Complementar no 141, de 2012');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('46','Transferências Fundo a Fundo aos Municípios à conta de recursos de que trata o art. 25 da Lei Complementar no 141, de 2012');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('50','Transferências a Instituições Privadas sem Fins Lucrativos');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('60','Transferências a Instituições Privadas com Fins Lucrativos');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('67','Execução de Contrato de Parceria Público-Privada - PPP');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('70','Transferências a Instituições Multigovernamentais');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('71','Transferências a Consórcios Públicos mediante contrato de rateio');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('72','Execução Orçamentária Delegada a Consórcios Públicos');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('73','Transferências a Consórcios Públicos mediante contrato de rateio à conta de recursos de que ratam os §§ 1o e 2o do art. 24 da Lei Complementar no 141, de 2012');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('74','Transferências a Consórcios Públicos mediante contrato de rateio à conta de recursos de que rata o art. 25 da Lei Complementar no 141, de 2012');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('75','Transferências a Instituições Multigovernamentais à conta de recursos de que tratam os §§ 1o e 2o do art. 24 da Lei Complementar no 141, de 2012');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('76','Transferências a Instituições Multigovernamentais à conta de recursos de que trata o art. 25 da Lei Complementar no 141, de 2012');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('80','Transferências ao Exterior');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('90','Aplicações Diretas');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('91','Aplicação Direta Decorrente de Operação entre Órgãos, Fundos e Entidades Integrantes dos Orçamentos Fiscal e da Seguridade Social');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('93','Aplicação Direta Decorrente de Operação de Órgãos, Fundos e Entidades Integrantes dos Orçamentos Fiscal e da Seguridade Social com Consórcio Público do qual o Ente Participe');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('94','Aplicação Direta Decorrente de Operação de Órgãos, Fundos e Entidades Integrantes dos Orçamentos Fiscal e da Seguridade Social com Consórcio Público do qual o Ente Não Participe');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('95','Aplicação Direta à conta de recursos de que tratam os §§ 1o e 2o do art. 24 da Lei Complementar no 141, de 2012');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('96','Aplicação Direta à conta de recursos de que trata o art. 25 da Lei Complementar no 141, de 2012');
INSERT INTO MODALIDADE (MODALIDADE_ID, MODALIDADE_NOME) VALUES ('99','Reserva de Contingência');
